# windows: $env:PWD = (Get-Location) 
#         (刪掉變數 Remove-Item Env:PWD，查看變數 Get-ChildItem Env: )
# linux有內建PWD，不用建立變數

#docker compose up -d --build

#docker compose --profile chat --profile embedding --profile tts --profile stt  up -d

x-gpu-reservation: &gpu-reservation
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

name: local_ai
services:

  control:
    image: control-plane:latest
    container_name: control
    runtime: nvidia
    build:
      context: ./services/control
      dockerfile: Dockerfile
      args:
        BUILD_DIR: ${PWD} 
    environment:
      - BUILD_DIR=${PWD}
    ports:
      - "${CONTROL_PORT}:${CONTROL_PORT}"
    env_file:
      - .env
    volumes:
      - ${IN_DOCKER_USE_DOCKER}
      - ${COMPOSE_PATH}:/app/docker-compose.yml
      - ${ENV_PATH}:/app/.env
      - ${COMPOSE_STATE_PATH}:/app/app/static/app/compose_state.json
      - ${CHAT_MODEL_PATH}:/app/models/chat
      - ${EMBEDDING_MODEL_PATH}:/app/models/embedding
      - ${TTS_MODEL_PATH}:/app/models/tts
      - ${STT_MODEL_PATH}:/app/models/stt

  license:
    image: license-server:latest
    build: ./services/license
    container_name: license
    volumes:
      - ./license.key:/license.key

  chat:
    image: vllm/vllm-openai:latest
    container_name: chat
    <<: *gpu-reservation
    volumes:
      - ${CHAT_MODEL_PATH}:/root/.cache/huggingface
    command:
      [
        "${CHAT_MODEL}",
        "--gpu-memory-utilization", "${CHAT_GPU_UTIL}",
        "--enable-chunked-prefill",
        "--dtype", "float16",
        "--disable-frontend-multiprocessing",
        "--trust-remote-code"
      ]
    profiles: ["chat"]

  embedding:
    image: embedding-openai:latest
    container_name: embedding
    build: ./services/embedding
    <<: *gpu-reservation
    environment:
      - MODEL_PATH=${EMBEDDING_MODEL}
    volumes:
      - ${EMBEDDING_MODEL_PATH}:/root/.cache/huggingface
    profiles: ["embedding"]

  tts:
    image: cosyvoice-openai:latest
    container_name: tts
    build: ./services/tts
    <<: *gpu-reservation
    environment:
      - PRELOAD_MODELS=${TTS_MODEL}
    volumes:
      - ${TTS_MODEL_PATH}:/workspace/CosyVoice/pretrained_models
      - ${TTS_ASSET_PATH}:/workspace/CosyVoice/asset
    profiles: ["tts"]

  stt:
    image: fasterwhisper-openai:latest
    container_name: stt
    build: ./services/stt
    <<: *gpu-reservation
    environment:
      - WHISPER__MODEL=${STT_MODEL}
    volumes:
      - ${STT_MODEL_PATH}:/root/.cache/huggingface
    profiles: ["stt"]
