#給docker內部使用

name: local_ai
services:
  chat:
    image: vllm/vllm-openai:latest
    container_name: chat
    <<: *gpu-reservation
    volumes:
      - ${CHAT_MODEL_PATH_IN_CONTROL}:/root/.cache/huggingface
    command:
      [
        "${CHAT_MODEL}",
        "--gpu-memory-utilization", "${CHAT_GPU_UTIL}",
        "--enable-chunked-prefill",
        "--dtype", "float16",
        "--disable-frontend-multiprocessing",
        "--trust-remote-code"
      ]
    profiles: ["chat"]

  embedding:
    image: embedding-openai:latest
    container_name: embedding
    <<: *gpu-reservation
    environment:
      - MODEL_PATH=${EMBEDDING_MODEL}
    volumes:
      - ${EMBEDDING_MODEL_PATH_IN_CONTROL}:/root/.cache/huggingface
    profiles: ["embedding"]

  tts:
    image: cosyvoice-openai:latest
    container_name: tts
    <<: *gpu-reservation
    environment:
      - PRELOAD_MODELS=${TTS_MODEL}
    volumes:
      - ${TTS_MODEL_PATH_IN_CONTROL}:/workspace/CosyVoice/pretrained_models
      - ${TTS_ASSET_PATH_IN_CONTROL}:/workspace/CosyVoice/asset
    profiles: ["tts"]

  stt:
    image: fasterwhisper-openai:latest
    container_name: stt
    <<: *gpu-reservation
    environment:
      - WHISPER__MODEL=${STT_MODEL_IN_CONTROL}
    volumes:
      - ${STT_MODEL_PATH}:/root/.cache/huggingface
    profiles: ["stt"]