#給docker內部使用

name: local_ai
services:
  chat:
    image: vllm/vllm-openai:latest
    container_name: chat
    environment:
      - NVIDIA_VISIBLE_DEVICES=${CHAT_GPU_ID:-0}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes:
      - ${CHAT_MODEL_PATH_IN_CONTROL}:/root/.cache/huggingface
    command:
      [
        "${CHAT_MODEL}",
        "--gpu-memory-utilization", "${CHAT_GPU_UTIL}",
        "--enable-chunked-prefill",
        "--dtype", "float16",
        "--disable-frontend-multiprocessing",
        "--trust-remote-code"
      ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 15
      start_period: 60s
    profiles: ["chat"]

  embedding:
    image: embedding-openai:latest
    container_name: embedding
    environment:
      - MODEL_PATH=${EMBEDDING_MODEL}
      - NVIDIA_VISIBLE_DEVICES=${EMBEDDING_GPU_ID:-0}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes:
      - ${EMBEDDING_MODEL_PATH_IN_CONTROL}:/root/.cache/huggingface
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    profiles: ["embedding"]

  tts:
    image: cosyvoice-openai:latest
    container_name: tts
    environment:
      - PRELOAD_MODELS=${TTS_MODEL}
      - NVIDIA_VISIBLE_DEVICES=${TTS_GPU_ID:-0}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes:
      - ${TTS_MODEL_PATH_IN_CONTROL}:/workspace/CosyVoice/pretrained_models
      - ${TTS_ASSET_PATH_IN_CONTROL}:/workspace/CosyVoice/asset
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 45s
    profiles: ["tts"]

  stt:
    image: fasterwhisper-openai:latest
    container_name: stt
    environment:
      - WHISPER__MODEL=${STT_MODEL_IN_CONTROL}
      - NVIDIA_VISIBLE_DEVICES=${STT_GPU_ID:-0}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes:
      - ${STT_MODEL_PATH}:/root/.cache/huggingface
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    profiles: ["stt"]